version: "3"
  
services:
    flask:
        container_name: flask
        build:
            context: ./flask
            dockerfile: dockerfile
        ports:
            - 5000:5000
        networks:
            - mynet
        environment:
            TZ: Asia/Taipei
            SERVER_PORT: ${DOCKER_SERVER_PORT}
        restart: always

    nginx:
        container_name: nginx
        build:
            context: ./nginx
            dockerfile: dockerfile
        ports:
            - ${DOCKER_NGINX_PORT}:80
        depends_on:
            - flask
        networks:
            - mynet
        environment:
            CONTAINER_NAME: flask
            SERVER_PORT: ${DOCKER_SERVER_PORT}
        command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
        restart: always

    mysql:
        container_name: mysql
        build: 
            context: ./mysql
            dockerfile: dockerfile
        volumes:
            - ./data/mysql/data:/var/lib/mysql
            - ./mysql/init:/docker-entrypoint-initdb.d/
            - ./mysql/sql:/opt/sql
        environment:
            - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
        ports:
            - ${MYSQL_PORT_NUMBER}:3306
        restart: always
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
        mynet: