FROM nginx:1.16.0-perl
LABEL maintainer="Herry"

RUN mkdir -p /usr/share/nginx/html/js
ADD ./nginx.conf /etc/nginx/nginx.conf.template

RUN rm /etc/nginx/conf.d/default.conf
RUN rm -rf /etc/nginx/nginx.conf
RUN rm -rf /usr/share/nginx/html/index.html

COPY . /usr/share/nginx/html