FROM python:3.8

ENV PROJECT_PATH /home/flask

RUN mkdir -p ${PROJECT_PATH}
WORKDIR ${PROJECT_PATH}
COPY . ${PROJECT_PATH}
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

EXPOSE ${SERVER_PORT}
CMD ["uwsgi", "--ini", "uwsgi.ini"]